package com.github.fruitdrivendevelopers.letMeGuide.repository

import com.github.fruitdrivendevelopers.letMeGuide.entity.AttractionDescription
import org.springframework.data.jpa.repository.JpaRepository

interface AttractionDescriptionRepository: JpaRepository<AttractionDescription, String>